### ISSUE TITLE
Compiling extension schema

### ISSUE THREAD

**Issue by vladsrynty** [bseddon/XBRL#14]
With every xbrl report file I get extension schema, which states what forms (presentation networks?) are available for particular business. With your help I can get all the necessary reports. 

I am trying to improve the speed and came up with the following idea. Instead of using extension schema with every report I created a file which has all the possible forms instead. Then I compiled it.

Every time I need a report I parse the extension schema and get the list of available forms (from xsd:appinfo/link).
I create instance with compiled schema and validateDFR returns all possible networks.

I create reports for available forms only:

```
$instance = XBRL_Instance::FromInstanceDocument($xbrlFileName, $compiledTaxonomyFile);

$listOfAvailableForms = parseExtensionSchema();
$dfr = new \XBRL_DFR( $instanceTaxonomy );
$presentationNetworks = $dfr->validateDFR( $formulas );
if (in_array($listOfAvailableForms, $presentationNetworks))
{
    getReportFields();
}

```
Is is a bit speedier than compiling extension taxonomy (and fixing Estonian extension taxonomy file by adding missing role imports), but still takes 2-3 seconds on my laptop.

To be honest I am not interested in full HTML reporting. I only look for fields from balance sheet and income statement.

I would be very thankful if you could share your thoughts on how could I make it faster..

**Comment by bseddon** [comment]
Hi Vladimir

Your idea of creating a taxonomy with all the form is good.  The US GAAP taxonomy provides and entry point like this for the US companies.  It means I can compile the 'all' entry point and use it for all the user submissions.  However, it is not a complete solution because as well as using the forms from the US GAAP taxonomy US companies can create their own concepts and whole new forms.  This means the company extension taxonomy must be compiled or it is possible the output will not include the concepts and forms defined by the company.  You can see an example of Microsoft's extension taxonomy here.

 
![us-gaap](https://user-images.githubusercontent.com/1221824/95025147-b0b1fd00-067f-11eb-8ea2-c45561f4c882.png)


Does the Estonian tax authority allow companies to add new concepts and forms?  If not, that's a good thing because it means your approach should work in all cases.

When using the DFR it does a lot of extra work to validate the structure of forms and to compute formula (if there are any) so it will be slower.  If you only need to reliably select specific such as the major items on the balance sheet, income statement and cashflow then take another look at the report.php file of the example application.  

The example that is part of the XBRL processor distribution was created based on the requirements of a user in Denmark (it's why the example refers to DK taxonomy stuff).  Like you, the user only wants to get the correct values for specific concepts and does not want to report the whole instance document so the ideas there may work for you.

If you are no longer compiling because you have created a taxonomy with all of the form and you are not using the DFR code to present the whole instance document that's about as fast as its going to go.

Bill

**Comment by bseddon** [comment]
No further comment so closing
