### ISSUE TITLE
Reverse Lookup?

### ISSUE THREAD

**Issue by sideshot** [bseddon/XBRL#17]
Any chance your code can do a reverse lookup?  For instance, parsing a JSON 10-Q and supplying the ReferenceName.  Can it return the master class?  (like roll-up?)

**Comment by bseddon** [comment]
At the moment there is no support for the JSON format.  It's not something that's planned for the near future.  The main purpose of the code is not to retrieve a value from a document but instead to be able to validate the structure of the document and the facts it contains.  That is, make sure the instance document is consistent with the taxonomy it claims to use.

If you need to get a value from a JSON 10-Q instance document it should be a simple as referencing the fact concept.  For example, if I use the SEC end point to retrieve facts for a company (I'm using the company with CIK 0000821002 because when I visited the EDGAR site just now it was the company that reported a 10-Q most recently):

https://data.sec.gov/api/xbrl/companyfacts/CIK0000821002.json

This is not a 10-Q JSON file but the format is similar and the principle remains the same.  With the JSON in $ap its possible to retrieve a fact by its concept name.  This is a name defined by the FASB in the US GAAP XBRL taxonomies they issue.

```php
$facts = file_get_contents( $CIK_URL );
$ap = $facts['facts']['us-gaap']['AccountsPayableCurrent']['units']['USD'];
```

$ap will be an array which can be queried for the appropriate period and then a value selected.  When using this end point values are listed with the oldest first so to retrieve the most recent 'Accounts Payable, Current' value:

```php
$recent = $ap[ count( $ap ) -1 ];
```

My apologies if I have missed your point.  However, at the moment there is no support for JSON.  There is also little motivation as the SEC converts all submissions to an XML format whether the submission uses iXBRL, JSON or CSV.  As a result, for the foreseeable future it will be possible to retrieve a submitted 10-Q (or K) instance document from the SEC in an XML format.

**Comment by sideshot** [comment]
I really appreciate your insight here.  The problem I'm having is being able to roll up the data because I can't seem to find factual relations between the meanings.  This seems to be because companies don't all report the same metrics.  

For instance,
Not All companies will have a line item for 'AssetsCurrent' but they will have what appears to be sub-classes of ''AssetsCurrent''.  So I'm trying to find the key to be able to roll-up data to get the answers needed.

I'm not sure if it's because I don't understand xsd correctly, or if my downloading the 'Bulk Data' has caused me to run into these issues.  

P.S - I'm willing to send you some coffee money for taking the time to point me in the right direction.

**Comment by bseddon** [comment]
All taxonomies describe the relationship(s) between concepts.  You can see the structure implied by any taxonomy visually using the [Yeti](https://xbrlview.fasb.org/) viewer. When prompted, select a taxonomy such as us gaap 2022 and it will show the concepts hierarchy which is initially grouped into statements and disclosures. The screenshot shows the current assets line item and the concepts that contribute to it.

I don't know about the document you are working with but instance documents are **supposed** to include the roll up values not just the leaf values.  Indeed the SEC will run checks on instance documents within a submission before accepting them to confirm, among other things, that the rollups exist and show the correct accumulation.  Now it may be that these rollup values are not included in JSON documents.

![yeti](https://user-images.githubusercontent.com/1221824/172599662-f397312c-9ca7-4f81-bdc9-3c41a5df13a6.jpg)

Maybe the safe thing for you to do is to interrogate the corresponding XBRL taxonomy document to extract the rollup information then apply it to the values you have.  This project can help access the information needed.  The project uses the rollup information to validate XML instance documents.  One of the validation checks is to apply the calculation (rollup) rules described by the taxonomy to the fact values in an instance document and confirm the accumulated total agrees with the corresponding rollup total fact value.  In your case you will be able to use the rules to generate a total.

**Comment by bseddon** [comment]
PS I use the term 'concept' and 'line item' interchangeably.  In the specification the things that define an account, like 'Assets, Current' are referred to a 'concepts'.  In the years since its definition the terminology, as it is presented to consumers, has changed slightly.  Now accounts are referred to a 'line items' as you can see in the Yeti screenshot.

**Comment by sideshot** [comment]
This is great.

Here is a quick example I found.

![image](https://user-images.githubusercontent.com/2152810/172618103-573811b7-fdfe-4d74-9742-1795da35792f.png)

https://data.sec.gov/api/xbrl/companyfacts/CIK0001477333.json

Some companies have CostsAndExpenses in their report.    However, in the above example, they have the child elements and not the parent.  

Example only includes:
CostOfRevenue
OperatingExpenses

Others will have CostsAndExpenses and not CostOfRevenue.

Do you think your project could be altered to Return the Tree for a given name?

**Comment by bseddon** [comment]
Yes, it does seem as if this source mixes and matches the facts included.  I guess its not surprising as the facts are for various periods and the taxonomies will have changed over those periods.  The changes will not be huge but change for example to reflect new legislation.

Yes, it is likely to be possible to discover the tree associated with any concept.  There are two ways to do this.  However, it may not be worth it if the concept names do not match exactly the names in the taxonomy.  Plus, its not clear that all the data does exist.

The most recent Cloudflare filing (that's the CIK included in the link you sent) can be found here:

https://www.sec.gov/Archives/edgar/data/0001477333/000147733322000031/0001477333-22-000031-index.htm

If you look in the file [cloud-20220331_htm.xml](https://www.sec.gov/Archives/edgar/data/1477333/000147733322000031/cloud-20220331_htm.xml) you will be able to find out which taxonomy Cloudflare used when preparing their submission.  This may be a more reliable source.  Its the one I would use but, perhaps, only because I don't know enough about the content of the JSON objects available from the SEC.

The taxonomy will include one or more files called calculation linkbases.  The calculation linkbases contain the rollup information.  In addition, the Cloudflare submission includes an additional [calculation linkbase](https://www.sec.gov/Archives/edgar/data/1477333/000147733322000031/cloud-20220331_cal.xml) to identify any additional concepts they have created and show how they should rollup into one of the US GAAP concepts.
