### ISSUE TITLE
VariableSet evaluated twice, second time with wrong context

### ISSUE THREAD

**Issue by tim-vandecasteele** [bseddon/XBRL#7]
@bseddon I got into a pretty weird problem, that's almost exactly as described in here https://github.com/bseddon/XBRL/blob/develop/Formulas/Evaluation.php#L241

When executing 
```
$formulas = new XBRL_Formulas();
if ( !$formulas->processFormulasAgainstInstances( $instance, null, null, null ) ) {
  echo "Consistency error\n";
}
```
against the Belgian Tax Taxonomy, the assertion in `be-tax-f-nrcorp-2420-2019-04-30-assertion.xml` is executed twice. Once regularly, and the next time, with a limited set, making it actually fail.

It seems that you added an `$evaluated` boolean to fix exactly that https://github.com/bseddon/XBRL/blob/develop/Formulas/Evaluation.php#L197 but this variable is in comment. I couldn't see in the history why that would be the case.

Sadly it's not that easy to give an easy file to reproduce, but if needed I can carefully craft one.

**Comment by bseddon** [comment]
It will be great if you are able to create an instance document for me or know of a location the regulator uses to host the company submissions (like the [Edgar system on the US SEC site](https://www.sec.gov/edgar/searchedgar/webusers.htm)).  

I'm struggling to see how I will be able to follow along and offer you some support without being able to exercise formulas against an instance document of some kind.  Even if the document contains  only zero values.  Given that it should be possible for me to manufacture some data or at least see errors.

In the meantime I'll revisit the conformance test mentioned in the comment you reference.

**Comment by tim-vandecasteele** [comment]
Please find two blank xbrl files attached. They don't really contain data, and all values are 0, but it should give you an idea. The first one fails the assertion correctly(so uncommenting the evaluate line doesn't have any effect, because it doesn't contain the elements the assertion checks for). The second one has the elements but shows the error, but if you uncomment the evaluate line, the error disappears (and the variable set isn't validated twice).

[blank.xbrl.txt](https://github.com/bseddon/XBRL/files/3596705/blank.xbrl.txt)
[blank_error_evaluate.xbrl.txt](https://github.com/bseddon/XBRL/files/3596745/blank_error_evaluate.xbrl.txt)

**Comment by bseddon** [comment]
Thanks for the files. I'll try to understand them (the elements not the text/labels).

The conformance test in the comments you reference is 22180 and has a description of "Tests of bind to empty sequence processing".  If your example is the same maybe it, too, is an example of binding to an empty set.   

The specific test that lead to the need for $evaluated and lead to the comment is V-10.  It's descriptions is:

> Three numeric variables each can bind to number when absent, different combinations of absent missing facts show dynamic evaluation ordering of the binding process to produce results.  If only static evaluation ordering is used then there will be missing results.  There are no inter-dependencies between the fact variables.

The example formula you reference does use variables that bind as a sequence and use empty sequences as fallbacks so may the two are related.

**Comment by bseddon** [comment]
I agree that it seems the line should not be commented.  Uncommenting the line has no effect on the conformance tests and corrects the problem as you have seen.  I guess it was commented because while it seemed like it should be there, I have had no case that needed to use it  until now.

The change has been pushed to the dev branch.

I've seen a problem that can occur when validating formulas if the target of an arc is in a different linkbase.  An example of where this happens is with the parameter definitions that are collected in a separate linkbase (be-tax-f-parameters-2019-04-30.xml).  A source linkbase (say containing formulas and assertions) may be loaded before the targets are available because they targets are in a linkbase that is not yet loaded.  In this case validation errors are reported incorrectly.  It does not affect the integrity of the formulas just validation error reporting.

**Comment by bseddon** [comment]
OK, I am mistaken by the final comment above.  This is a manifestation of the [first issue](https://github.com/tim-vandecasteele/xbrl-experiment/commit/3610466123ffe936fd45b5a0299fa97baa4699ac) you reported.  Implementing your suggested fix addresses this point.

**Comment by tim-vandecasteele** [comment]
@bseddon I'm a bit puzzled investigating a very similar issue. 

The file attached also makes a double evaluation happen for assertion 5007. I'm knee deep into the investigation, but the thing most hampering me is that I don't really understand why the evaluation needs to be recursive.

I created this minimal file to reproduce the issue, but the more `ExemptWriteDownDebtClaim` tags you add with correct dimensions, the more times the evaluation is executed.

[f-wddc-5007-wrong.xbrl.txt](https://github.com/bseddon/XBRL/files/3601957/f-wddc-5007-wrong.xbrl.txt)

**Comment by bseddon** [comment]
I'll take a look this evening.  If I have nothing before I have to pack in I'll let you know and will pick it up on Friday if you have not resolved it.  

The recursion occurs because variables are evaluated within variables.  The first step is to create an ordered set of variables that take into account any dependencies (say a fact variable that relies on the result of a general variable).  Then variables are evaluated in turn.  The advantage of using recursion is that the evaluation state of the variables can be passed into the same function.  The state can be changed in the function and because it has been passed in changes will not affect the next iteration (if there is one).  Why might there be more that one iteration on a variable?  Because the variable can be bound as a sequence not a value in which case each element of the sequence (if there is more than one) needs to be evaluated independently.

A for loop could be used but then the interim state will need to be recorded some place.  My original implementation wayback when used for loops but I got tangled and find using recursion easier.

**Comment by bseddon** [comment]
Is it the assertion in the file be-tax-f-wddc-5007-2019-04-30-assertion.xml. There is also a '5007' formula in be-tax-f-wddc-5007-2019-04-30-formula.xml.  The name of the attached file suggests you are referring to the assertion which has the label and id 'f-wddc-5007' while the formula has a label and id of 'f-wddc-5007-formula'.

**Comment by tim-vandecasteele** [comment]
It's indeed the assertion that's going wrong. When running `processFormulasAgainstInstances`, I get two messages on the file that the sum is wrong. I would only expect one message, and would expect it to return true.

Thanks for the explanation about the recursion. The weird thing is that with it is that the recursion also triggers the creation of messages twice `evaluateResult()` is triggered twice on value assertion, meaning `processMessages` is also triggered twice, resulting in multiple messages where I would expect only one.

**Comment by bseddon** [comment]
I have stepped through the example.  There appears to be an issue with the result of the call to
```php
$binding->partitionFacts( $this->variableSet );
```
(which is on line 176 of Evaluation.php) when fact variable v_ExemptWriteDownDebtClaimStart is evaluated.  As I see it, the desired result is that there is one sequence with two members so that when the general variable CalculatedAmountExemptWriteDownDebtClaimStartTotal is evaluated is sums the two sequence members (100, 100) to produce the required result that can be matched later with $ExemptWriteDownDebtClaimStartTotal that has the correct value of 200.  

You see an error result because the sequence elements are being compared separately so 100 != 200.  You see two evaluations because the two members in the sequence are being evaluated separately which is not what's desired.

I will carry on for a little longer looking at the partitionFacts facts method but its likely I will run out of time before there is an answer today.  If I get chance to have a look tomorrow I will,  If not, I'll pick it up on Friday (unless you have the solution by then),

**Comment by bseddon** [comment]
I think this issue is to do with interpretation of the specification.  The formula specification details binding as a sequence can be found [here](http://www.xbrl.org/Specification/variables/REC-2009-06-22/variables-REC-2009-06-22.html#sec-binding-as-a-sequence).

My reading of the specificaiton says that a bound sequence cannot contain facts that have identical aspect values (concept name, period, unit, dimensions, etc) unless the fact variable has a @matches value of 'true' (the spec says the attribute must exist and cannot be 'false').  

As the matches attribute does not exist on the fact variable and as the aspect values of the 2 facts are identical they cannot exist in the same sequence.  As a result, the partitionFacts function returns two sequences each with a single value.

If I modify the fact variable to add a matches attribute then the sequence returned by the partitionFacts function is correct and the computed value of CalculatedAmountExemptWriteDownDebtClaimStartTotal is 200.

One of us has this wrong.  Probably me.  So I need to think hard about what the specification is saying and find out how I am misinterpreting it.

**Comment by tim-vandecasteele** [comment]
I might have lead you on a goose chase here, as I played around with the actual file, cutting it down. The contexts were actually different in my original file. Let me recreate an example where that's the case.

**Comment by tim-vandecasteele** [comment]
If I understand correctly, this file should be according to the specifications, but still poses the problem.

[f-wddc-5007-wrong.xbrl.txt](https://github.com/bseddon/XBRL/files/3602940/f-wddc-5007-wrong.xbrl.txt)

**Comment by bseddon** [comment]
Your previous example was perfectly OK.  The issue is to do with the processor's definition of binding as a sequence.  It is different to the one used by the authors of the taxonomy.  On Friday I will use a third party formula processor to see what result it generates.

**Comment by tim-vandecasteele** [comment]
Ok, then I got that wrong. I thought you said the issue was that there were two facts with exactly the same context, which was the case in the first file. The second file has a different dimension, so the 'aspect values' are not the same as far as I understand XBRL 😀. Let me know if I can assist further, because I'm quite out of my zone here 😄

**Comment by bseddon** [comment]
Yes, sorry, I was trying to respond too quickly. I'll look into and try to explain more tomorrow.  However, my belief is that the issue is that fact variable may not be correctly defined for the intended purpose.  I will be able to confirm that (or not) tomorrow.

**Comment by bseddon** [comment]
It will be great if you can try this small modification to the formula linkbase.  It works for me. Of course it will because it is in line with my interpretation of the formula specification!  

I am going to be trying with a different formula processor.  If it accepts the BE formula without complaining I know the problem is with my processor and my interpretation of the binding-as-a-sequence section (4.1) of the variables document of the XBRL formula specification.  If it also tries to evaluate each fact then the issues is with the taxonomy.  I'll know tomorrow.

[be-tax-f-wddc-5007-2019-04-30-assertion.xml.txt](https://github.com/bseddon/XBRL/files/3606953/be-tax-f-wddc-5007-2019-04-30-assertion.xml.txt)

**Comment by bseddon** [comment]
By the way, the reason your revised instance document does not make any difference to the result is that the dimension *member* has changed not the dimension.  It's the dimension that's the aspect so a change to the member is material and so to the processor the facts are indistinguishable.

**Comment by tim-vandecasteele** [comment]
I tried the adaptated formula linkbase, and it validates without problems now, so your reasoning aligns with the code 😄 

Reading up on the aspect tests, I follow your last comment with respect to the dimensions and why it didn't really makes sense. Thanks for the explanation!

**Comment by bseddon** [comment]
On reflection, my comment yesterday is not correct.  The member IS important.  You see that it is used when the content of two different contexts are compared on line 536 of ./vendor/lyquidity/xbrl/Formulas/FactVariableBinding.php.

When I make the explicit dimension members different in the second "wrong" example it is sufficient for the facts to be identified as different.  However, when the members of  **typed** dimensions are different, this difference is not detected.  I'm investigating why this is so.

Unfortunately the other formula processor I hoped to use is unable to handle the BE taxonomy '5007' assertion formula so that didn't work out.  It fails with a run-time type validation error.

**Comment by tim-vandecasteele** [comment]
It's a pity that the other formula processor didn't work, but it looks like you're onto something here. The first example was definitely something of my creation and not a proper file that would be submitted. The second example with the different dimensions is closer. 
Thanks for looking into this, and let me know if you need additional information. (I'll play a bit around with it myself based on your insights)

**Comment by bseddon** [comment]
This may be fixed now.  Thanks for your patience and help finding the issue, tracking down the problem and fixing it.  The changes have been to XBRL_Equalities.php.  

This file implements a class whose members implement comparisons for various entities such as contexts (c-equal), periods (p-equal), units, segments, scenarios, dimensions, etc..  There was a note in this file, in the function seqment_equals on line 397, from Feb 2018 letting me know that typed member comparisons were not implemented.  That certainly explains why your second "wrong" examples does not work as the difference between contexts I2 and I4 is the typed member value.

To add support for comparing typed dimensions it was necessary to improve and fix issues with the function compare_arrays().  Changes to this file do seem to fix the issue.  Because none of these changes break any of the conformance suite tests the changes have been pushed to the dev repository.

Thanks for taking to time to create the two "wrong" example instance documents.  Really helpful. Now there is an explanation for the problems exposed by both examples.  

You were correct that the first example shows a different problem.  In this example, both facts are identical and the only way to see just a single evaluation is to modify the fact variable of the formula to add @matches and set its value to true.  However, as you realized, this is a different problem.

In your second example, the contexts I2 and I4 differ by the value of the typed dimension member.  As this was not being found, the processor regarded the two different facts as being the same.  Because the specification does not allow sequence bindings to contain duplicate facts (unless @matches is used) these facts were grouped into two different sequences (of one member each) which led to the unexpected multiple evaluations.

Now because the different typed member values are compared, the processor treats the facts as being different so both can appear in the same sequence leading to just one evaluation.

**Comment by tim-vandecasteele** [comment]
That's great! Thank you so much for the investigation, the fix, and the explanation.
I tested it with several of the other assertions that had a similar problem, and this fixes all of that.

I'll keep you updated if I encounter any more issues.
